config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get  "/search" => "search#index"
  get  "/search/autocomplete" => "search#autocomplete"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
  get 'login', to: redirect("/auth/github")
  get 'logout', to: 'sessions#destroy'

  resources :sessions
  resources :users
  resources :recommendations, except: :show
  resources :terms

  match ":status", to: 'application#server_error', constraints: { status: /5\d{2}/ }, via: :all
  match '*path', via: :all, to: 'application#not_found'
end

app/models/recommendation.rb
require 'file_size_validator'

class Recommendation < ActiveRecord::Base
  include Recommendable
  mount_uploader :image, RecommendationImageUploader

  has_many :terms, dependent: :destroy
  accepts_nested_attributes_for :terms, allow_destroy: true

  validates :name,
    presence: { is: true, message: "Namnet måste fyllas i." },
    uniqueness: { is: true, message: "Det finns redan en rekommendation med det namnet." },
    length: { minimum: 2, maximum: 32 }
  validates :link,
    presence: { is: true, message: "Länk måste fyllas i." },
    uniqueness: { is: true, message: "Länken finns redan." },
    length: { minimum: 4, maximum: 255 }
  validates :description,
    length: { maximum: 125 }
  validates_associated :terms

  validates :image,
    file_size: { maximum: 1.megabytes.to_i }

  before_save do
    # Add protocol if missing
    self.link = "http://#{link}" unless link.match(/^https?:\/\//)
    self.link.strip!
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]
  before_action { add_body_class('admin') }
  before_action :authorize

  def index
    @recommendations = Recommendation.order("lower(name)").includes(:terms)
  end

  def new
    @recommendation = Recommendation.new
    @recommendation.terms << Term.new
  end

  def edit
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to recommendations_path, notice: 'Rekommendationen sparades' }
        format.json { render action: 'show', status: :created, location: @recommendation }
      else
        format.html { render action: 'new' }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to recommendations_path, notice: 'Rekommendationen sparades' }
        format.json { render action: 'show', status: :ok, location: @recommendation }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:name, :link, :description,
        :image, :image_cache, :remove_image,
        terms_attributes: [:id, :_destroy, :name ])
    end
end

app/views/recommendations/_fields_for_terms.html.haml
= t.input :name, label: false, wrapper: :addon do
  = t.input_field :_destroy, as: :hidden
  = t.input_field :name, class: "form-control"
  %span.input-group-btn
    %button.btn.btn-default.remove{ type: :button }
      %span.m-icon-close-0

app/views/recommendations/_form.html.haml
= simple_form_for @recommendation, html: { class: "basic", id: "edit-recommendation" } do |f|
  = f.error_notification class: "warning"

  .form-group
    = f.input :name
    = f.input :link
    = f.input :description
    = f.input :image, as: :image_preview, input_html: { preview_version: :thumb }
    - if @recommendation.image.present?
      = f.input :remove_image, as: :boolean, label: false, inline_label: true

    %h2.group-title Sökord
    .terms
      = f.simple_fields_for :terms do |t|
        = render "fields_for_terms", t: t
      .form-group
        %span.control-label
        .controls
          = add_terms_button "Lägg till", f

  .form-group
    %span.control-label
    .controls
      = f.button :submit, class: 'btn btn-primary'
      - unless @recommendation.new_record?
        = link_to "Radera", @recommendation, class: "btn btn-danger", data: { confirm: 'Är du säker?', method: :delete }
      = link_to t('actions.cancel'), recommendations_path, class: "btn btn-default"

app/views/recommendations/edit.html.haml
- title "Redigera rekommendation"
%section.box.form
  %h1.box-title= h1
  .box-content
    = render 'form'

app/views/recommendations/index.html.haml
- title "Rekommendationer"
%section.box.index
  %h1.box-title= h1
  .box-content
    .table-wrapper
    %table.full
      %thead
        %tr
          %th Namn
          %th.terms Sökord
          %th.link Länk
          %th.delete
      %tbody
        - @recommendations.each do |recommendation|
          %tr
            %td= link_to recommendation.name, edit_recommendation_path(recommendation), rel: 'nofollow'
            %td.terms= recommendation.terms.map(&:name).join(", ")
            %td.link= link_to recommendation.link, recommendation.link
            %td.delete= link_to "Radera", recommendation, method: :delete, class: "btn btn-danger btn-xs", data: { confirm: 'Är du säker?' }

        %tr
          %td{ colspan: 4 }
            .actions= link_to "Lägg till", new_recommendation_path, class: "btn btn-default", rel: 'nofollow'

app/views/recommendations/new.html.haml
- title "Ny rekommendation"
%section.box.form
  %h1.box-title= h1
  .box-content
    = render 'form'