config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get  "/search" => "search#index"
  get  "/search/autocomplete" => "search#autocomplete"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
  get 'login', to: redirect("/auth/github")
  get 'logout', to: 'sessions#destroy'

  resources :sessions
  resources :users
  resources :recommendations, except: :show
  resources :terms

  match ":status", to: 'application#server_error', constraints: { status: /5\d{2}/ }, via: :all
  match '*path', via: :all, to: 'application#not_found'
end

app/views/layouts/_breadcrumbs.html.haml
%nav.breadcrumbs
  %ul
    %li= link_to "Start", APP_CONFIG['base_url']
    %li= link_to "Sök", root_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %meta{ name: 'robots', content: 'noindex, nofollow' }
    %title= "#{APP_CONFIG['title_suffix']} – Sök"
    / <WA disable link>
    /[if IE]
      %meta{ "http-equiv" => "X-UA-Compatible", "content" => "IE=edge"}
    /[if lte IE 8]
      = javascript_include_tag "#{APP_CONFIG['assets_url_base']}html5shiv-printshiv.js"
    = stylesheet_link_tag "#{APP_CONFIG['assets_url_base']}malmo.css", media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    /[if lte IE 8]
      = stylesheet_link_tag "#{APP_CONFIG['assets_url_base']}legacy/ie8.css", media: 'all'
    %noscript= stylesheet_link_tag "#{APP_CONFIG['assets_url_base']}icons.fallback.css", media: 'all'
    %link{ rel: 'icon', type: 'image/x-icon', href: "#{APP_CONFIG['assets_url_base']}favicon.ico" }
    = csrf_meta_tags
  %body.mf-v4{ class: @body_classes }
    - if current_user
      %nav.app
        = link_to "Rekommendationer", recommendations_path, rel: 'nofollow'
        = link_to "Sökord", terms_path, rel: 'nofollow'
        = link_to "#{current_user.name}", users_path, class: "username", rel: 'nofollow'
        = link_to "Logga ut", logout_path, class: "logout", rel: 'nofollow'
    .wrapper
      = render "layouts/breadcrumbs"
      - flash.each do |key, value|
        %p{ class: "flash #{key}" }= value
      = yield
    = javascript_include_tag "#{APP_CONFIG['assets_url_base']}malmo.js"
    = javascript_include_tag 'application'